### ISSUE TITLE
Error: Empty value for parameter 'pull_number': undefined

### ISSUE THREAD

**Issue by cajwo8** [wyozi/contextual-qa-checklist-action#16]
Whenever I merge pull requests into the master branch, the checklist fails for this error. It passes upon the initial push of the pull request, though. I wonder if this is related to https://github.com/probot/probot/issues/1168? Would you be able to help me with this error?

**Comment by wyozi** [comment]
Hey. Sounds weird, is the action using just the `pull_request_target` (or `pull_request`) event?

**Comment by wyozi** [comment]
Released new version which might fix this

**Comment by cajwo8** [comment]
We're using the pull_request event

This is from the yml file 

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```
