### ISSUE TITLE
Issue with regular expression in the path

### ISSUE THREAD

**Issue by jpetot** [wyozi/contextual-qa-checklist-action#25]
In a `CHECKLIST.yml`, I found something strange, that looks like a regex issue. 
This setting wasn't working:
```yaml
paths:
  "folder1/folder2/**.py":
    - Does anything need to be updated?
```
Whereas the following works great for me:
```yaml
paths:
  "folder1/folder2/**/*.py":
    - Does anything need to be updated?
```

But in your documentation you recommend something like this (`"src/components/**.js":`).

What is wrong with my code?
